version: '3.7'

services: 
  postgres:
    image: 'postgres'
    container_name: 'pg'
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test